version: '3'
services:

  nginx:
    image: fabiohigor/desafio2-nginx
    build:
      dockerfile: Dockerfile
      context: nginx
    tty: true
    container_name: nginx
    ports: 
      - "8080:80"
    networks:
      - cyclenet
    depends_on:
          - db
          - app

  app:
    image: fabiohigor/desafio2-node
    build: 
      dockerfile: Dockerfile.node
      context: node
    tty: true
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 190s -wait-retry-interval 5s sh -c "npm install && node index.js"
    volumes: 
      - ./node/app:/usr/src/app
      # - /usr/src/app/node_modules #volume anonimo (link simbolico)
    ports:
      - "3000:3000"
    networks:
      - cyclenet
    depends_on:
      - db

  db: 
    image: mysql:8-debian
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    networks:
      - cyclenet

networks:
  cyclenet:
    driver: bridge